export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER = 'FETCH_USER';
export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_CANCEL = 'EDIT_USER_CANCEL';

export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS = 'FETCH_TASKS';
export const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
