export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER = 'FETCH_USER';

export const EDIT_USER_INIT = 'EDIT_USER_INIT';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_CANCEL = 'EDIT_USER_CANCEL';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';
export const EDIT_USER_START = 'EDIT_USER_START';
export const EDIT_USER = 'EDIT_USER';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS = 'FETCH_USERS';

export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS = 'FETCH_TASKS';

export const FETCH_TASK_START = 'FETCH_TASK_START';
export const FETCH_TASK_FAIL = 'FETCH_TASK_FAIL';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK = 'FETCH_TASK';

export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL';
export const CREATE_TASK_CANCEL = 'CREATE_TASK_CANCEL';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK = 'CREATE_TASK';

export const CHANGE_TASK_START = 'CHANGE_TASK_START';
export const CHANGE_TASK_FAIL = 'CHANGE_TASK_FAIL';
export const CHANGE_TASK_SUCCESS = 'CHANGE_TASK_SUCCESS';
export const CHANGE_TASK = 'CHANGE_TASK';

export const ADD_TASK_COMMENT_START = 'ADD_TASK_COMMENT_START';
export const ADD_TASK_COMMENT_FAIL = 'ADD_TASK_COMMENT_FAIL';
export const ADD_TASK_COMMENT_SUCCESS = 'ADD_TASK_COMMENT_SUCCESS';
export const ADD_TASK_COMMENT = 'ADD_TASK_COMMENT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_TOGGLE = 'AUTH_TOGGLE';

export const OPEN_CHAT = 'OPEN_CHAT';
export const CLOSE_CHAT = 'CLOSE_CHAT';
export const FETCH_CHATROOM_START = 'FETCH_CHATROOM_START';
export const FETCH_CHATROOM_FAIL = 'FETCH_CHATROOM_FAIL';
export const FETCH_CHATROOM_SUCCESS = 'FETCH_CHATROOM_SUCCESS';
export const SEND_MESSAGE = 'SEND_MESSAGE';
